project_id = "openreview-edge-functions"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://app.openreview.jp"
additional_redirect_urls = ["http://localhost:3000", "https://app.openreview.jp"]
jwt_expiry = 3600
enable_signup = true